server.port: 8080
logging:
  level:
    root: INFO
    org.springframework.r2dbc: OFF

spring:
  application:
    name: checkout-service
  config:
    activate:
      on-profile: docker
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/checkout_db
    username: postgres
    password: test123
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
  data:
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
